//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.18 at 06:20:14 PM CST 
//


package mas.aml.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	        (author): Precious Pearl A. Sano <pr3_cious_15@yahoo.com>
 * 				
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="screeningResult" type="{http://mas/aml/soap/model}screeningResult" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "screeningResult"
})
@XmlRootElement(name = "customerFormReply")
public class CustomerFormReply {

    protected ScreeningResult screeningResult;

    /**
     * Gets the value of the screeningResult property.
     * 
     * @return
     *     possible object is
     *     {@link ScreeningResult }
     *     
     */
    public ScreeningResult getScreeningResult() {
        return screeningResult;
    }

    /**
     * Sets the value of the screeningResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScreeningResult }
     *     
     */
    public void setScreeningResult(ScreeningResult value) {
        this.screeningResult = value;
    }

}
