//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.18 at 06:20:14 PM CST 
//


package mas.aml.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	        (author): Precious Pearl A. Sano <pr3_cious_15@yahoo.com>
 * 	getCustomerFormCommandRequest version : 1.0
 * 				
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="individualTag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstNameEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="middleNameEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastNameEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="placeOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nationality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contactNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="identificationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="identificationNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrRoom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrFloor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrBlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrLot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrBuildingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrVillage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrHousingProject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resAddrCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyNameEn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyTelNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyPrimaryContactNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyDateOfIncorporation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyCertificationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyCertificationNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyRegistrationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companyRegistrationNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrRoom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrFloor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrBlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrLot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrBuildingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrVillage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrHousingProject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comAddrCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="countryCodeIncorporation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="countryCodeOperation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedSigners" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="legal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="management" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="regulatory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="companySourceIncome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="natureOfCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="individualSourceIncome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="natureOfIndividualSourceIncome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clientAcctId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clientType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "individualTag",
    "firstNameEn",
    "middleNameEn",
    "lastNameEn",
    "dateOfBirth",
    "placeOfBirth",
    "nationality",
    "contactNo",
    "gender",
    "identificationType",
    "identificationNo",
    "resAddrRoom",
    "resAddrFloor",
    "resAddrBlock",
    "resAddrLot",
    "resAddrBuildingName",
    "resAddrStreet",
    "resAddrVillage",
    "resAddrHousingProject",
    "resAddrDistrict",
    "resAddrCity",
    "resAddrCountryCode",
    "companyNameEn",
    "companyType",
    "companyTelNo",
    "companyPrimaryContactNo",
    "companyDateOfIncorporation",
    "companyCertificationType",
    "companyCertificationNo",
    "companyRegistrationType",
    "companyRegistrationNo",
    "comAddrRoom",
    "comAddrFloor",
    "comAddrBlock",
    "comAddrLot",
    "comAddrBuildingName",
    "comAddrStreet",
    "comAddrVillage",
    "comAddrHousingProject",
    "comAddrDistrict",
    "comAddrCity",
    "comAddrCountryCode",
    "countryCodeIncorporation",
    "countryCodeOperation",
    "authorizedSigners",
    "legal",
    "management",
    "owner",
    "regulatory",
    "companySourceIncome",
    "natureOfCompany",
    "individualSourceIncome",
    "natureOfIndividualSourceIncome",
    "role",
    "clientId",
    "clientAcctId",
    "clientType"
})
@XmlRootElement(name = "getCustomerFormCommandRequest")
public class GetCustomerFormCommandRequest {

    protected String individualTag;
    protected String firstNameEn;
    protected String middleNameEn;
    protected String lastNameEn;
    protected String dateOfBirth;
    protected String placeOfBirth;
    protected String nationality;
    protected String contactNo;
    protected String gender;
    protected String identificationType;
    protected String identificationNo;
    protected String resAddrRoom;
    protected String resAddrFloor;
    protected String resAddrBlock;
    protected String resAddrLot;
    protected String resAddrBuildingName;
    protected String resAddrStreet;
    protected String resAddrVillage;
    protected String resAddrHousingProject;
    protected String resAddrDistrict;
    protected String resAddrCity;
    protected String resAddrCountryCode;
    protected String companyNameEn;
    protected String companyType;
    protected String companyTelNo;
    protected String companyPrimaryContactNo;
    protected String companyDateOfIncorporation;
    protected String companyCertificationType;
    protected String companyCertificationNo;
    protected String companyRegistrationType;
    protected String companyRegistrationNo;
    protected String comAddrRoom;
    protected String comAddrFloor;
    protected String comAddrBlock;
    protected String comAddrLot;
    protected String comAddrBuildingName;
    protected String comAddrStreet;
    protected String comAddrVillage;
    protected String comAddrHousingProject;
    protected String comAddrDistrict;
    protected String comAddrCity;
    protected String comAddrCountryCode;
    protected String countryCodeIncorporation;
    protected String countryCodeOperation;
    protected String authorizedSigners;
    protected String legal;
    protected String management;
    protected String owner;
    protected String regulatory;
    protected String companySourceIncome;
    protected String natureOfCompany;
    protected String individualSourceIncome;
    protected String natureOfIndividualSourceIncome;
    protected String role;
    protected String clientId;
    protected String clientAcctId;
    protected String clientType;

    /**
     * Gets the value of the individualTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualTag() {
        return individualTag;
    }

    /**
     * Sets the value of the individualTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualTag(String value) {
        this.individualTag = value;
    }

    /**
     * Gets the value of the firstNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstNameEn() {
        return firstNameEn;
    }

    /**
     * Sets the value of the firstNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstNameEn(String value) {
        this.firstNameEn = value;
    }

    /**
     * Gets the value of the middleNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleNameEn() {
        return middleNameEn;
    }

    /**
     * Sets the value of the middleNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleNameEn(String value) {
        this.middleNameEn = value;
    }

    /**
     * Gets the value of the lastNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastNameEn() {
        return lastNameEn;
    }

    /**
     * Sets the value of the lastNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastNameEn(String value) {
        this.lastNameEn = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfBirth(String value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the contactNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNo() {
        return contactNo;
    }

    /**
     * Sets the value of the contactNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNo(String value) {
        this.contactNo = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the identificationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationType() {
        return identificationType;
    }

    /**
     * Sets the value of the identificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationType(String value) {
        this.identificationType = value;
    }

    /**
     * Gets the value of the identificationNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationNo() {
        return identificationNo;
    }

    /**
     * Sets the value of the identificationNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationNo(String value) {
        this.identificationNo = value;
    }

    /**
     * Gets the value of the resAddrRoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrRoom() {
        return resAddrRoom;
    }

    /**
     * Sets the value of the resAddrRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrRoom(String value) {
        this.resAddrRoom = value;
    }

    /**
     * Gets the value of the resAddrFloor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrFloor() {
        return resAddrFloor;
    }

    /**
     * Sets the value of the resAddrFloor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrFloor(String value) {
        this.resAddrFloor = value;
    }

    /**
     * Gets the value of the resAddrBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrBlock() {
        return resAddrBlock;
    }

    /**
     * Sets the value of the resAddrBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrBlock(String value) {
        this.resAddrBlock = value;
    }

    /**
     * Gets the value of the resAddrLot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrLot() {
        return resAddrLot;
    }

    /**
     * Sets the value of the resAddrLot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrLot(String value) {
        this.resAddrLot = value;
    }

    /**
     * Gets the value of the resAddrBuildingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrBuildingName() {
        return resAddrBuildingName;
    }

    /**
     * Sets the value of the resAddrBuildingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrBuildingName(String value) {
        this.resAddrBuildingName = value;
    }

    /**
     * Gets the value of the resAddrStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrStreet() {
        return resAddrStreet;
    }

    /**
     * Sets the value of the resAddrStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrStreet(String value) {
        this.resAddrStreet = value;
    }

    /**
     * Gets the value of the resAddrVillage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrVillage() {
        return resAddrVillage;
    }

    /**
     * Sets the value of the resAddrVillage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrVillage(String value) {
        this.resAddrVillage = value;
    }

    /**
     * Gets the value of the resAddrHousingProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrHousingProject() {
        return resAddrHousingProject;
    }

    /**
     * Sets the value of the resAddrHousingProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrHousingProject(String value) {
        this.resAddrHousingProject = value;
    }

    /**
     * Gets the value of the resAddrDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrDistrict() {
        return resAddrDistrict;
    }

    /**
     * Sets the value of the resAddrDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrDistrict(String value) {
        this.resAddrDistrict = value;
    }

    /**
     * Gets the value of the resAddrCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrCity() {
        return resAddrCity;
    }

    /**
     * Sets the value of the resAddrCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrCity(String value) {
        this.resAddrCity = value;
    }

    /**
     * Gets the value of the resAddrCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResAddrCountryCode() {
        return resAddrCountryCode;
    }

    /**
     * Sets the value of the resAddrCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResAddrCountryCode(String value) {
        this.resAddrCountryCode = value;
    }

    /**
     * Gets the value of the companyNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyNameEn() {
        return companyNameEn;
    }

    /**
     * Sets the value of the companyNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyNameEn(String value) {
        this.companyNameEn = value;
    }

    /**
     * Gets the value of the companyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * Sets the value of the companyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyType(String value) {
        this.companyType = value;
    }

    /**
     * Gets the value of the companyTelNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyTelNo() {
        return companyTelNo;
    }

    /**
     * Sets the value of the companyTelNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyTelNo(String value) {
        this.companyTelNo = value;
    }

    /**
     * Gets the value of the companyPrimaryContactNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyPrimaryContactNo() {
        return companyPrimaryContactNo;
    }

    /**
     * Sets the value of the companyPrimaryContactNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyPrimaryContactNo(String value) {
        this.companyPrimaryContactNo = value;
    }

    /**
     * Gets the value of the companyDateOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyDateOfIncorporation() {
        return companyDateOfIncorporation;
    }

    /**
     * Sets the value of the companyDateOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyDateOfIncorporation(String value) {
        this.companyDateOfIncorporation = value;
    }

    /**
     * Gets the value of the companyCertificationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCertificationType() {
        return companyCertificationType;
    }

    /**
     * Sets the value of the companyCertificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCertificationType(String value) {
        this.companyCertificationType = value;
    }

    /**
     * Gets the value of the companyCertificationNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCertificationNo() {
        return companyCertificationNo;
    }

    /**
     * Sets the value of the companyCertificationNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCertificationNo(String value) {
        this.companyCertificationNo = value;
    }

    /**
     * Gets the value of the companyRegistrationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyRegistrationType() {
        return companyRegistrationType;
    }

    /**
     * Sets the value of the companyRegistrationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyRegistrationType(String value) {
        this.companyRegistrationType = value;
    }

    /**
     * Gets the value of the companyRegistrationNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyRegistrationNo() {
        return companyRegistrationNo;
    }

    /**
     * Sets the value of the companyRegistrationNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyRegistrationNo(String value) {
        this.companyRegistrationNo = value;
    }

    /**
     * Gets the value of the comAddrRoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrRoom() {
        return comAddrRoom;
    }

    /**
     * Sets the value of the comAddrRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrRoom(String value) {
        this.comAddrRoom = value;
    }

    /**
     * Gets the value of the comAddrFloor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrFloor() {
        return comAddrFloor;
    }

    /**
     * Sets the value of the comAddrFloor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrFloor(String value) {
        this.comAddrFloor = value;
    }

    /**
     * Gets the value of the comAddrBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrBlock() {
        return comAddrBlock;
    }

    /**
     * Sets the value of the comAddrBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrBlock(String value) {
        this.comAddrBlock = value;
    }

    /**
     * Gets the value of the comAddrLot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrLot() {
        return comAddrLot;
    }

    /**
     * Sets the value of the comAddrLot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrLot(String value) {
        this.comAddrLot = value;
    }

    /**
     * Gets the value of the comAddrBuildingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrBuildingName() {
        return comAddrBuildingName;
    }

    /**
     * Sets the value of the comAddrBuildingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrBuildingName(String value) {
        this.comAddrBuildingName = value;
    }

    /**
     * Gets the value of the comAddrStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrStreet() {
        return comAddrStreet;
    }

    /**
     * Sets the value of the comAddrStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrStreet(String value) {
        this.comAddrStreet = value;
    }

    /**
     * Gets the value of the comAddrVillage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrVillage() {
        return comAddrVillage;
    }

    /**
     * Sets the value of the comAddrVillage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrVillage(String value) {
        this.comAddrVillage = value;
    }

    /**
     * Gets the value of the comAddrHousingProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrHousingProject() {
        return comAddrHousingProject;
    }

    /**
     * Sets the value of the comAddrHousingProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrHousingProject(String value) {
        this.comAddrHousingProject = value;
    }

    /**
     * Gets the value of the comAddrDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrDistrict() {
        return comAddrDistrict;
    }

    /**
     * Sets the value of the comAddrDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrDistrict(String value) {
        this.comAddrDistrict = value;
    }

    /**
     * Gets the value of the comAddrCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrCity() {
        return comAddrCity;
    }

    /**
     * Sets the value of the comAddrCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrCity(String value) {
        this.comAddrCity = value;
    }

    /**
     * Gets the value of the comAddrCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComAddrCountryCode() {
        return comAddrCountryCode;
    }

    /**
     * Sets the value of the comAddrCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComAddrCountryCode(String value) {
        this.comAddrCountryCode = value;
    }

    /**
     * Gets the value of the countryCodeIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCodeIncorporation() {
        return countryCodeIncorporation;
    }

    /**
     * Sets the value of the countryCodeIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCodeIncorporation(String value) {
        this.countryCodeIncorporation = value;
    }

    /**
     * Gets the value of the countryCodeOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCodeOperation() {
        return countryCodeOperation;
    }

    /**
     * Sets the value of the countryCodeOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCodeOperation(String value) {
        this.countryCodeOperation = value;
    }

    /**
     * Gets the value of the authorizedSigners property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedSigners() {
        return authorizedSigners;
    }

    /**
     * Sets the value of the authorizedSigners property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedSigners(String value) {
        this.authorizedSigners = value;
    }

    /**
     * Gets the value of the legal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegal() {
        return legal;
    }

    /**
     * Sets the value of the legal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegal(String value) {
        this.legal = value;
    }

    /**
     * Gets the value of the management property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagement() {
        return management;
    }

    /**
     * Sets the value of the management property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagement(String value) {
        this.management = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the regulatory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatory() {
        return regulatory;
    }

    /**
     * Sets the value of the regulatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatory(String value) {
        this.regulatory = value;
    }

    /**
     * Gets the value of the companySourceIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanySourceIncome() {
        return companySourceIncome;
    }

    /**
     * Sets the value of the companySourceIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanySourceIncome(String value) {
        this.companySourceIncome = value;
    }

    /**
     * Gets the value of the natureOfCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatureOfCompany() {
        return natureOfCompany;
    }

    /**
     * Sets the value of the natureOfCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatureOfCompany(String value) {
        this.natureOfCompany = value;
    }

    /**
     * Gets the value of the individualSourceIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualSourceIncome() {
        return individualSourceIncome;
    }

    /**
     * Sets the value of the individualSourceIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualSourceIncome(String value) {
        this.individualSourceIncome = value;
    }

    /**
     * Gets the value of the natureOfIndividualSourceIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatureOfIndividualSourceIncome() {
        return natureOfIndividualSourceIncome;
    }

    /**
     * Sets the value of the natureOfIndividualSourceIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatureOfIndividualSourceIncome(String value) {
        this.natureOfIndividualSourceIncome = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the clientAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientAcctId() {
        return clientAcctId;
    }

    /**
     * Sets the value of the clientAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientAcctId(String value) {
        this.clientAcctId = value;
    }

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientType(String value) {
        this.clientType = value;
    }

}
