//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.18 at 06:20:14 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mas/aml/soap/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mas.aml.soap.model;
